NOTA1BI=float(input("DIGITE A NOTA DO PRIMEIRO BIMESTRE: "))
NOTA2BI=float(input("DIGITE A NOTA DO SEGUNDO BIMESTRE: "))
NOTA3BI=float(input("DIGITE A NOTA DO TERCEIRO BIMESTRE: "))
NOTA4BI=float(input("DIGITE A NOTA DO QUARTO BIMETRE: "))
MEDIA=(NOTA1BI+NOTA2BI+NOTA3BI+NOTA4BI)/4
print("A MEDIA BIMESTRAL É: ",MEDIA)
